# Generated by Django 3.2.25 on 2025-05-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250527_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
