# Generated by Django 3.2.25 on 2025-05-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dailylog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='tags',
        ),
        migrations.AddField(
            model_name='dailylog',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
